### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by ximanta** [jimkang/dependency-parser#2]
Using node v6..9.2 and npm 3.10.9 on Windows

npm install fails at rollup --config with

    at Function.Module._resolveFilename (module.js:469:15)
    at Function.requireRelative.resolve (E:\simanta\Immersive\intent-parser-master\node_modules\require-relative\index.js:30:17)
    at resolve (E:\simanta\Immersive\intent-parser-master\node_modules\modify-babel-preset\lib\serialize.js:25:26)
    at findAndRemove (E:\simanta\Immersive\intent-parser-master\node_modules\modify-babel-preset\lib\serialize.js:67:11)
    at E:\simanta\Immersive\intent-parser-master\node_modules\modify-babel-preset\lib\serialize.js:111:13
    at Array.map (native)
    at loadPreset (E:\simanta\Immersive\intent-parser-master\node_modules\modify-babel-preset\lib\serialize.js:103:29)
    at module.exports (E:\simanta\Immersive\intent-parser-master\node_modules\modify-babel-preset\index.js:97:19)
    at Object.<anonymous> (E:\simanta\Immersive\intent-parser-master\node_modules\babel-preset-es2015-rollup\index.js:3:18)
    at Module._compile (module.js:570:32) code: 'MODULE_NOT_FOUND' } babel-runtime
Error transforming E:\simanta\Immersive\intent-parser-master\src\intent-parser.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
Error: Error transforming E:\simanta\Immersive\intent-parser-master\src\intent-parser.js with 'babel' plugin: It looks like your Babel configuration specifies a module transformer. Please disable it. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at preflightCheck (E:\simanta\Immersive\intent-parser-master\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:46:104)
    at Object.transform$1 [as transform] (E:\simanta\Immersive\intent-parser-master\node_modules\rollup-plugin-babel\dist\rollup-plugin-babel.cjs.js:117:18)
    at E:\simanta\Immersive\intent-parser-master\node_modules\rollup\src\utils\transform.js:19:35
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
Type rollup --help for help, or visit https://github.com/rollup/rollup/wiki

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! intent-parser@1.0.10 build: `rollup --config`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the intent-parser@1.0.10 build script 'rollup --config'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the intent-parser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     rollup --config
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs intent-parser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls intent-parser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\simanta\Immersive\intent-parser-master\npm-debug.log

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v6.9.2
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! intent-parser@1.0.10 prepublish: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the intent-parser@1.0.10 prepublish script 'npm run build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the intent-parser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs intent-parser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls intent-parser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\simanta\Immersive\intent-parser-master\npm-debug.log

**Comment by jimkang** [comment]
Sorry about that; unfortunately, I don’t have access to a Windows machine to debug this. Let me know if you figure anything more out, or if anyone else wants to take this on.
